name: Provision AWS Infrastructure using Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  SWAN_AWS_REGION: "ap-southeast-1"
  TF_VAR_swan_ci_iam_role_arn: ${{ secrets.SWAN_CI_IAM_ROLE_ARN }}

permissions:
  id-token: write # id-token write permission is needed to use OIDC

jobs:
  swan_terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: swan_terraform/swan_environments/swan_production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.SWAN_CI_IAM_ROLE_ARN }}
          aws-region: ${{ env.SWAN_AWS_REGION }}

      - name: Terraform Init
        run: terraform init -input=false -upgrade

      - name: Terraform Format Check
        run: terraform fmt -check -diff

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -out=swan_tfplan -var-file=prod.tfvars

      - name: Upload Terraform Plan Artifact
        uses: actions/upload-artifact@v6
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        with:
          name: swan_tfplan
          path: swan_terraform/swan_environments/swan_production/swan_tfplan

  swan_terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: swan_terraform_plan
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    defaults:
      run:
        working-directory: swan_terraform/swan_environments/swan_production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.SWAN_CI_IAM_ROLE_ARN }}
          aws-region: ${{ env.SWAN_AWS_REGION }}

      - name: Terraform Init
        run: terraform init -input=false -upgrade

      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v7
        with:
          name: swan_tfplan
          path: swan_terraform/swan_environments/swan_production

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false swan_tfplan
