name: Terraform Destroy

on:
  workflow_dispatch:

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  swan_terraform_destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: swan_terraform/swan_environments/swan_production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.14.3

      - name: Cache Terraform providers
        uses: actions/cache@v5
        with:
          path: swan_terraform/swan_environments/swan_production/.terraform/providers
          key: terraform-providers-${{ runner.os }}-${{ hashFiles('swan_terraform/swan_environments/swan_production/**/*.tf') }}
          restore-keys: terraform-providers-${{ runner.os }}-

      - name: Terraform Init
        run: terraform init -input=false -upgrade

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false -var-file=prod.tfvars