name: Terraform Destroy

on:
  workflow_dispatch:

env:
  SWAN_AWS_REGION: "ap-southeast-1"
  TF_VAR_swan_ci_role_arn: ${{ secrets.SWAN_CI_ROLE_ARN }}
  TF_VAR_swan_user_arn: ${{ secrets.SWAN_USER_ARN }}

permissions:
  id-token: write # id-token write permission is needed to use OIDC

jobs:
  swan_terraform_destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: swan_terraform/swan_environments/swan_production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Cache Terraform providers
        uses: actions/cache@v5
        with:
          path: |
            swan_terraform/swan_environments/swan_production/.terraform/providers
            swan_terraform/swan_environments/swan_production/.terraform.lock.hcl
          key: terraform-providers-${{ runner.os }}-${{ hashFiles('swan_terraform/swan_environments/swan_production/**/*.tf') }}
          restore-keys: terraform-providers-${{ runner.os }}-

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v5.1.1
        with:
          role-to-assume: ${{ secrets.SWAN_CI_ROLE_ARN }}
          aws-region: ${{ env.SWAN_AWS_REGION }}

      - name: Terraform Init
        run: terraform init -input=false -upgrade

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false -var-file=prod.tfvars