name: Provision AWS Infrastructure using Terraform

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  swan_terraform_plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: swan_terraform/swan_environments/swan_production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false

      - name: Terraform Format Check
        run: terraform fmt -check -diff

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan
        run: terraform plan -input=false -out=swan_tfplan -var-file=prod.tfvars

      - name: Upload Terraform Plan Artifact
        uses: actions/upload-artifact@v6
        with:
          name: swan_tfplan
          path: swan_terraform/swan_environments/swan_production/swan_tfplan

  swan_terraform_apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: swan_terraform_plan
    defaults:
      run:
        working-directory: swan_terraform/swan_environments/swan_production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init -input=false

      - name: Download Terraform Plan Artifact
        uses: actions/download-artifact@v7
        with:
          name: swan_tfplan
          path: swan_terraform/swan_environments/swan_production

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false swan_tfplan